### ISSUE TITLE
Conekta_ResourceNotFoundError

### ISSUE THREAD

**Issue by idlikesometea** [luisesalazar/Conekta-codeigniter#1]
Estoy intentando usar tu implementación para integrar Conekta en mi proyecto de CodeIgniter, pero siempre que intento realizar una operación, la que sea, incluyendo las que pones de ejemplo me marca este error de que no encuentra el recurso, tienes alguna idea de por qué me está saliendo esto? Muchas gracias y saludos

**Comment by luisesalazar** [comment]
Estas usando CI 3.0?, usaste la implementacion que puse aqui?

**Comment by idlikesometea** [comment]
Es la misma implementación pero el proyecto en el que lo estoy integrando es de CI 2.0.3, esa debe ser la causa del problema, es posible adaptar la implementación o crees que sea necesario mudar a CI 3?

**Comment by luisesalazar** [comment]
Ah ok, porque yo acabo de bajar la implementacion, le cambie las llaves de conekta en el archivo config/conekta.php y funciono.
Ahora: no creo q este amarrada a la version 3.0, yo use esa solo para demostracion, pero si se requiere php mayor igual a 5.3

**Comment by luisesalazar** [comment]
lo que se podria hacer es bajar esta implementacion, y bajar el framework 2.0.3 de CI y copiar de la carpeta config el archivo conekta, la carpeta conekta de libraries y el controlador welcome de controllers, despues probar para revisar con detalle en donde es incompatible. La diferencia mas notable de CI  >= 3.0 vs < 3.0 esque los controladores y modelos ahora son con la letra inicial en mayusculas. saludos

**Comment by idlikesometea** [comment]
Ya chequé y lo que faltaba era agregar el conekta_api_version en al configuracion en el arcivho de config/conekta, ya se conecta con la API, gracias por la ayuda
